name: hf_transformer
model_type: huggingface
model_config:
  pretrained_model_name_or_path: "Qwen/Qwen3-4B-Instruct-2507"
  cache_dir: "${oc.env:ROOT_DIR}/models"
  device_map: auto
  low_cpu_mem_usage: true
  torch_dtype: bfloat16
  # attn_implementation: sdpa

generation_config:
  do_sample: true
  temperature: 0.6
  top_k: 20
  top_p: 0.95
  min_p: 0.