name: browsecomp_plus
dataset_config:
  path: decrypted_browsecomp_plus.jsonl
  cache_dir: "${oc.env:ROOT_DIR}/data"

grader_model_config:
  name: openai
  is_async: false
  model_config:
    model: gpt-4.1-mini-2025-04-14
    use_vision: false
    generation_config:
      max_output_tokens: 4096
      parallel_tool_calls: false
      temperature: 1

num_distractors: 20
ambiguous_titles: false
include_titles_in_prompt: true
max_doc_tokens: 4096  # 8192
prior_obs_not_in_state: false

num_train_samples: 700
num_val_samples: 30
num_test_samples: 100

max_steps: 20
max_tries: 1
seed: 0
split: train
system_prompt_choice: default
truncation_message: "Sorry, you have reached the maximum number of steps. Please try again."
